"""Export the star schema as CSVs for an external BI tool.

Power BI Desktop reads Parquet only through a Power Query step, and DuckDB only through an
ODBC driver, so flat CSV is the path with the fewest moving parts. This writes one file per
table into reports/bi_exports/ plus a short guide covering the relationships and measures to
build on top of them.

The CSVs are gitignored. They are derived from data/raw/Sample_Superstore.csv and rebuilt by
rerunning this module, so committing them would be storing the same numbers twice.

Run with: python -m src.export_bi (after python -m src.transform_star_schema)
"""

from __future__ import annotations

from pathlib import Path

import duckdb

from src.utils import (
    DIMENSION_TABLES,
    EXPORT_TABLES,
    FACT_TABLE,
    REPORTS_DIR,
    connect,
    require_star_schema,
    row_count,
)

EXPORT_DIR = REPORTS_DIR / "bi_exports"
GUIDE_PATH = EXPORT_DIR / "README.md"

# Fact column -> (dimension table, dimension column). Drives both the export guide and the
# relationships to build in the BI tool.
RELATIONSHIPS = {
    "customer_key": ("dim_customer", "customer_key"),
    "product_key": ("dim_product", "product_key"),
    "geography_key": ("dim_geography", "geography_key"),
    "order_date_key": ("dim_date", "date_key"),
    "ship_date_key": ("dim_date", "date_key"),
}

# From Appendix A of the project plan. Written out so they can be pasted rather than retyped.
DAX_MEASURES = [
    ("Total Sales", "SUM ( fact_sales[sales] )"),
    ("Total Profit", "SUM ( fact_sales[profit] )"),
    ("Profit Margin %", "DIVIDE ( [Total Profit], [Total Sales] )"),
    ("Avg Discount", "AVERAGE ( fact_sales[discount] )"),
    ("Loss-Making Lines %",
     "DIVIDE ( CALCULATE ( COUNTROWS ( fact_sales ), fact_sales[is_loss_making] = TRUE ), "
     "COUNTROWS ( fact_sales ) )"),
    ("YoY Sales Growth %",
     "VAR PriorYear =\n"
     "    CALCULATE ( [Total Sales], SAMEPERIODLASTYEAR ( dim_date[full_date] ) )\n"
     "RETURN\n"
     "    DIVIDE ( [Total Sales] - PriorYear, PriorYear )"),
]


# Binary floating point cannot represent most decimal money values exactly, so writing a
# double as text produces artefacts like 731.9399999999999 for what is really 731.94. Six
# places is past the precision of anything in this dataset, so rounding removes the noise
# without moving a single total: sales and profit sum to the same value to ten decimals
# either way. Parquet keeps the raw doubles, so nothing is lost for the Python side.
CSV_DECIMAL_PLACES = 6
FLOAT_TYPES = {"DOUBLE", "FLOAT", "REAL", "DECIMAL"}


def _select_list(con: duckdb.DuckDBPyConnection, table: str) -> str:
    """Column list for the export, rounding float columns to kill float-repr artefacts."""
    columns = con.execute(f"DESCRIBE {table}").fetchall()
    parts = []
    for name, column_type, *_ in columns:
        if any(column_type.upper().startswith(t) for t in FLOAT_TYPES):
            parts.append(f'round("{name}", {CSV_DECIMAL_PLACES}) AS "{name}"')
        else:
            parts.append(f'"{name}"')
    return ", ".join(parts)


def export_tables(con: duckdb.DuckDBPyConnection, directory: Path | None = None) -> dict[str, int]:
    """Write each star-schema table to CSV. Returns row counts by file name.

    DuckDB's CSV writer is used rather than pandas: it emits dates as YYYY-MM-DD, booleans as
    true/false, and nulls as empty fields, all of which Power BI's type detection reads
    correctly without a Power Query fixup.
    """
    require_star_schema(con)
    target = directory or EXPORT_DIR
    target.mkdir(parents=True, exist_ok=True)

    written = {}
    for table in EXPORT_TABLES:
        path = target / f"{table}.csv"
        con.execute(
            f"COPY (SELECT {_select_list(con, table)} FROM {table}) "
            "TO ? (FORMAT CSV, HEADER, DELIMITER ',')",
            [str(path)],
        )
        written[path.name] = row_count(con, table)
    return written


def build_guide(con: duckdb.DuckDBPyConnection) -> str:
    """A short setup note next to the files, so the manual BI step is not from memory."""
    lines = [
        "# Power BI extracts",
        "",
        "Generated by `python -m src.export_bi`. One CSV per star-schema table. The files are "
        "gitignored, so regenerate them after any change to the pipeline.",
        "",
        "## Files",
        "",
        "| File | Rows | Key | Role |",
        "| --- | ---: | --- | --- |",
        f"| `{FACT_TABLE}.csv` | {row_count(con, FACT_TABLE):,} | `row_id` | Fact, one row per order line |",
    ]
    roles = {
        "dim_customer": ("customer_key", "Customer and segment"),
        "dim_product": ("product_key", "Category, sub-category, product"),
        "dim_geography": ("geography_key", "City, state, region"),
        "dim_date": ("date_key", "Calendar, mark as the date table"),
    }
    for table in DIMENSION_TABLES:
        key, role = roles[table]
        lines.append(f"| `{table}.csv` | {row_count(con, table):,} | `{key}` | {role} |")

    lines += [
        "",
        "## Import",
        "",
        "In Power BI Desktop, Get Data > Text/CSV for each of the five files. The CSVs are "
        "UTF-8 with an ISO date format, so the default type detection is correct. Check that "
        "`postal_code` imports as a whole number and not text: 11 rows are blank, which can "
        "make the detector guess wrong.",
        "",
        "## Relationships",
        "",
        "Build these in Model view. All are one-to-many from the dimension to the fact, with "
        "single cross-filter direction.",
        "",
        "| From | To | Cardinality |",
        "| --- | --- | --- |",
    ]
    for fact_column, (dim_table, dim_column) in RELATIONSHIPS.items():
        lines.append(f"| `{dim_table}[{dim_column}]` | `fact_sales[{fact_column}]` | one-to-many |")

    lines += [
        "",
        "`dim_date` joins twice, on `order_date_key` and `ship_date_key`. Power BI allows only "
        "one active relationship between two tables, so make the order-date one active and "
        "leave the ship-date one inactive, reaching it with `USERELATIONSHIP` when a measure "
        "needs it. Mark `dim_date` as the date table using `full_date`, or the time "
        "intelligence functions below will not work.",
        "",
        "## Measures",
        "",
    ]
    for name, expression in DAX_MEASURES:
        lines += [f"**{name}**", "", "```dax", f"{name} = {expression}", "```", ""]

    lines += [
        "Format `Profit Margin %`, `Avg Discount`, `Loss-Making Lines %`, and "
        "`YoY Sales Growth %` as percentages. They return ratios rather than pre-multiplied "
        "numbers, so formatting is what makes them read correctly.",
        "",
        "## Report pages",
        "",
        "From Appendix A of the project plan:",
        "",
        "1. **Executive summary**: KPI cards, monthly trend line, region map.",
        "2. **Regional deep dive**: a Region by Category by Sub-Category matrix with "
        "conditional formatting on margin.",
        "3. **Discount impact**: discount against profit margin as a scatter with a trend "
        "line, plus a sub-category ranking by discount sensitivity.",
        "",
        "Add slicers for Region, Segment, Category, and Order Date that cross-filter all "
        "three pages.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    with connect(read_only=True) as con:
        written = export_tables(con)
        guide = build_guide(con)

    GUIDE_PATH.write_text(guide, encoding="utf-8", newline="\n")

    total_bytes = 0
    for name, rows in written.items():
        size = (EXPORT_DIR / name).stat().st_size
        total_bytes += size
        print(f"  {name:<22} {rows:>7,} rows  {size / 1024:>8,.0f} KB")
    print(f"\nwrote {len(written)} CSVs ({total_bytes / 1024 / 1024:.1f} MB) and "
          f"{GUIDE_PATH.name} to {EXPORT_DIR.relative_to(REPORTS_DIR.parent)}")


if __name__ == "__main__":
    main()
